import path from "node:path";
import type { GeneratedOutput, RepoFacts, Target } from "./types";
import { GENERATED_MARKER } from "./types";

export interface BuildOutputOptions {
  agentsOutputPath?: string;
}

interface CommandRow {
  purpose: string;
  command: string;
  source: string;
}

export function buildOutputs(
  facts: RepoFacts,
  targets: readonly Target[] = ["agents"],
  options: BuildOutputOptions = {}
): GeneratedOutput[] {
  const uniqueTargets = [...new Set(targets)];
  return uniqueTargets.map((target) => ({
    target,
    path: outputPathForTarget(facts.root, target, options),
    content: generateTargetMarkdown(target, facts)
  }));
}

export function outputPathForTarget(
  repoRoot: string,
  target: Target,
  options: BuildOutputOptions = {}
): string {
  if (target === "agents") {
    const output = options.agentsOutputPath ?? "AGENTS.md";
    return path.isAbsolute(output) ? output : path.resolve(repoRoot, output);
  }
  if (target === "copilot") {
    return path.resolve(repoRoot, ".github", "copilot-instructions.md");
  }
  if (target === "cursor") {
    return path.resolve(repoRoot, ".cursor", "rules", "repository.mdc");
  }
  return path.resolve(repoRoot, "CLAUDE.md");
}

export function generateTargetMarkdown(target: Target, facts: RepoFacts): string {
  if (target === "copilot") {
    return generateCopilot(facts);
  }
  if (target === "cursor") {
    return generateCursor(facts);
  }
  if (target === "claude") {
    return generateClaude(facts);
  }
  return generateAgents(facts);
}

export function generateAgents(facts: RepoFacts): string {
  return joinLines([
    "# AGENTS.md",
    GENERATED_MARKER,
    "",
    "## Overview",
    overviewText(facts),
    "",
    "## Detected Stack",
    ...detectedStackBullets(facts),
    "",
    "## Commands",
    ...commandTable(facts),
    "",
    "## Architecture Map",
    ...architectureBullets(facts),
    "",
    "## Coding Conventions",
    ...codingConventionBullets(facts),
    "",
    "## Testing Expectations",
    ...testingBullets(facts),
    "",
    "## Environment Notes",
    ...environmentBullets(facts),
    "",
    "## Safety Boundaries",
    ...safetyBullets(facts),
    "",
    "## Contribution Workflow",
    ...contributionBullets(facts)
  ]);
}

function generateCopilot(facts: RepoFacts): string {
  return joinLines([
    "# Copilot Instructions",
    GENERATED_MARKER,
    "",
    overviewText(facts),
    "",
    "## Repository Context",
    ...detectedStackBullets(facts),
    "",
    "## Preferred Commands",
    ...commandBullets(facts),
    "",
    "## Working Rules",
    ...codingConventionBullets(facts),
    ...testingBullets(facts),
    ...safetyBullets(facts)
  ]);
}

function generateCursor(facts: RepoFacts): string {
  return joinLines([
    "---",
    "description: Repository guidance generated by repo-to-agents",
    "globs: \"**/*\"",
    "alwaysApply: true",
    "---",
    GENERATED_MARKER,
    "",
    "# Repository Rules",
    "",
    overviewText(facts),
    "",
    "## Stack",
    ...detectedStackBullets(facts),
    "",
    "## Commands",
    ...commandBullets(facts),
    "",
    "## Architecture",
    ...architectureBullets(facts),
    "",
    "## Rules",
    ...codingConventionBullets(facts),
    ...testingBullets(facts),
    ...safetyBullets(facts)
  ]);
}

function generateClaude(facts: RepoFacts): string {
  return joinLines([
    "# CLAUDE.md",
    GENERATED_MARKER,
    "",
    overviewText(facts),
    "",
    "## Repository Snapshot",
    ...detectedStackBullets(facts),
    "",
    "## Commands To Prefer",
    ...commandBullets(facts),
    "",
    "## Architecture Map",
    ...architectureBullets(facts),
    "",
    "## Development Guidance",
    ...codingConventionBullets(facts),
    ...testingBullets(facts),
    ...environmentBullets(facts),
    ...safetyBullets(facts)
  ]);
}

function overviewText(facts: RepoFacts): string {
  const title = facts.readme?.title ? `README title: "${facts.readme.title}".` : "";
  const description = facts.readme?.description ? ` ${facts.readme.description}` : "";
  const base = `This is guidance for AI coding agents working in \`${facts.name}\`.`;
  return `${base}${title ? ` ${title}` : ""}${description}`.trim();
}

function detectedStackBullets(facts: RepoFacts): string[] {
  const packageManager = facts.packageJson?.packageManager;
  const bullets = [
    `- Languages: ${formatList(facts.languages)}.`,
    `- Frameworks and tools: ${formatList(facts.frameworks)}.`,
    `- Package manager: ${
      packageManager ? `${packageManager.name}${packageManager.version ? ` ${packageManager.version}` : ""} (${packageManager.source})` : "not detected"
    }.`,
    `- Config files: ${formatList(facts.configFiles)}.`,
    `- Test configuration: ${formatList(facts.testConfigs)}.`,
    `- CI workflows: ${formatList(facts.githubActions)}.`
  ];

  if (facts.python) {
    bullets.push(
      `- Python project: ${facts.python.projectName ?? "detected"} using ${facts.python.manager ?? "pip"}; requirements: ${formatList(
        facts.python.requirementsFiles
      )}; tools: ${formatList(facts.python.tools)}.`
    );
  }
  if (facts.go) {
    bullets.push(`- Go module: ${facts.go.modulePath ?? "detected"}.`);
  }
  if (facts.rust) {
    bullets.push(`- Rust package: ${facts.rust.packageName ?? "detected"}.`);
  }
  if (facts.docker) {
    bullets.push(
      `- Containers: Dockerfiles ${formatList(facts.docker.dockerfiles)}; compose files ${formatList(
        facts.docker.composeFiles
      )}.`
    );
  }
  return bullets;
}

function commandTable(facts: RepoFacts): string[] {
  const commands = inferCommands(facts);
  if (commands.length === 0) {
    return [
      "No standard commands were detected. Prefer documented project commands from the README or Makefile before adding new tooling."
    ];
  }

  return [
    "| Purpose | Command | Source |",
    "| --- | --- | --- |",
    ...commands.map((row) => `| ${escapeTable(row.purpose)} | \`${escapeBackticks(row.command)}\` | ${escapeTable(row.source)} |`)
  ];
}

function commandBullets(facts: RepoFacts): string[] {
  const commands = inferCommands(facts);
  if (commands.length === 0) {
    return ["- No standard commands were detected. Check the README before adding or changing tooling."];
  }
  return commands.map((row) => `- ${row.purpose}: \`${row.command}\` (${row.source}).`);
}

function architectureBullets(facts: RepoFacts): string[] {
  if (facts.directories.length === 0) {
    return ["- No common source directories were detected at the repository root."];
  }
  return facts.directories.map((entry) => `- \`${entry.path}/\`: ${entry.purpose}.`);
}

function codingConventionBullets(facts: RepoFacts): string[] {
  const bullets = [
    "- Match the existing project structure, naming, and formatting conventions in nearby files.",
    "- Keep changes focused on the requested behavior; avoid broad refactors unless they are required.",
    "- Prefer existing scripts, helpers, and configuration over introducing new tools."
  ];

  if (facts.tsconfig) {
    bullets.push("- For TypeScript, keep types explicit at module boundaries and preserve strict compiler compatibility.");
  }
  if (facts.frameworks.includes("ESLint")) {
    bullets.push("- Treat ESLint findings as required cleanup before handing work back.");
  }
  if (facts.frameworks.includes("Prettier")) {
    bullets.push("- Preserve Prettier-compatible formatting instead of hand-formatting large blocks.");
  }
  if (facts.python) {
    bullets.push("- For Python, follow the tooling declared in pyproject.toml or requirements files before adding alternatives.");
  }
  if (facts.go) {
    bullets.push("- For Go, run gofmt-compatible formatting and keep package boundaries idiomatic.");
  }
  if (facts.rust) {
    bullets.push("- For Rust, prefer cargo-managed workflows and keep public APIs documented when changed.");
  }
  return bullets;
}

function testingBullets(facts: RepoFacts): string[] {
  const bullets = [
    "- Add or update tests when behavior changes, especially for public APIs, CLI behavior, and data transformations.",
    "- Run the most specific detected test command first, then the broader suite before final handoff."
  ];

  const commands = inferCommands(facts).filter((row) => /test|check|lint|typecheck/i.test(row.purpose));
  if (commands.length > 0) {
    bullets.push(`- Relevant verification commands: ${commands.map((row) => `\`${row.command}\``).join(", ")}.`);
  }
  if (facts.githubActions.length > 0) {
    bullets.push("- Keep GitHub Actions passing; mirror CI commands locally when possible.");
  }
  return bullets;
}

function environmentBullets(facts: RepoFacts): string[] {
  const bullets: string[] = [];
  if (facts.packageJson?.packageManager) {
    bullets.push(`- Use ${facts.packageJson.packageManager.name} for Node.js dependency and script workflows.`);
  }
  if (facts.python?.manager) {
    bullets.push(`- Use ${facts.python.manager} for Python dependency workflows when Python changes are needed.`);
  }
  if (facts.docker?.composeFiles.length) {
    bullets.push("- Docker Compose files are present; prefer them for service dependencies when documented.");
  } else if (facts.docker?.dockerfiles.length) {
    bullets.push("- Dockerfiles are present; keep image changes small and reproducible.");
  }
  if (bullets.length === 0) {
    bullets.push("- No special runtime environment was detected. Document any new required services or secrets.");
  }
  bullets.push("- Never commit secrets, local environment files, dependency caches, or build output.");
  return bullets;
}

function safetyBullets(facts: RepoFacts): string[] {
  const generatedOrVendorDirs = facts.directories
    .map((entry) => entry.path)
    .filter((entry) => ["dist", "build", "coverage", "target", "vendor"].includes(entry));
  return [
    "- Do not overwrite user changes or generated instruction files unless the file contains the repo-to-agents marker or the user explicitly asks.",
    "- Keep destructive operations such as resets, forced pushes, and mass deletes out of normal workflows.",
    `- Avoid editing generated, vendored, or cache directories${generatedOrVendorDirs.length ? ` such as ${formatList(generatedOrVendorDirs)}` : ""}.`,
    "- Minimize dependency additions; justify any new dependency in the change summary."
  ];
}

function contributionBullets(facts: RepoFacts): string[] {
  const commands = inferCommands(facts);
  const verification = commands
    .filter((row) => /test|lint|typecheck|build|check/i.test(row.purpose))
    .map((row) => `\`${row.command}\``);
  return [
    "- Start from a clean branch and inspect existing issues or README guidance before changing behavior.",
    "- Implement the smallest coherent change, then update tests, docs, and examples that describe the changed behavior.",
    `- Before opening a PR, run ${verification.length > 0 ? verification.join(", ") : "the relevant project checks"}.`,
    "- In PR descriptions, summarize behavior changes, verification performed, and any follow-up risks."
  ];
}

function inferCommands(facts: RepoFacts): CommandRow[] {
  const rows: CommandRow[] = [];
  const packageManager = facts.packageJson?.packageManager?.name ?? "npm";
  const scripts = facts.packageJson?.scripts ?? {};

  if (facts.packageJson) {
    rows.push({ purpose: "Install dependencies", command: installCommand(packageManager), source: "package.json" });
  }

  const preferredScripts = ["dev", "start", "build", "test", "lint", "typecheck", "check", "format"];
  const scriptNames = [
    ...preferredScripts.filter((script) => scripts[script]),
    ...Object.keys(scripts)
      .filter((script) => !preferredScripts.includes(script))
      .sort()
  ];
  for (const script of scriptNames) {
    rows.push({
      purpose: `Package script: ${script}`,
      command: runScriptCommand(packageManager, script),
      source: `package.json scripts.${script}`
    });
  }

  if (facts.python) {
    if (facts.python.requirementsFiles.length > 0) {
      rows.push({
        purpose: "Install Python requirements",
        command: `${pythonInstallPrefix(facts.python.manager)} -r ${facts.python.requirementsFiles[0]}`,
        source: facts.python.requirementsFiles[0]
      });
    } else if (facts.python.pyproject) {
      rows.push({
        purpose: "Install Python project",
        command: pythonProjectInstallCommand(facts.python.manager),
        source: "pyproject.toml"
      });
    }
    if (facts.testConfigs.some((config) => /pytest|tox|nox|conftest/.test(config)) || facts.python.tools.includes("pytest")) {
      rows.push({ purpose: "Python tests", command: "pytest", source: "Python test configuration" });
    }
  }

  if (facts.go) {
    rows.push({ purpose: "Go tests", command: "go test ./...", source: "go.mod" });
  }
  if (facts.rust) {
    rows.push({ purpose: "Rust tests", command: "cargo test", source: "Cargo.toml" });
    rows.push({ purpose: "Rust build", command: "cargo build", source: "Cargo.toml" });
  }
  if (facts.make?.targets.length) {
    for (const target of facts.make.targets.slice(0, 10)) {
      rows.push({ purpose: `Make target: ${target}`, command: `make ${target}`, source: "Makefile" });
    }
  }
  if (facts.docker?.composeFiles.length) {
    rows.push({ purpose: "Run container services", command: "docker compose up --build", source: facts.docker.composeFiles[0] });
  }

  return dedupeCommands(rows);
}

function installCommand(manager: string): string {
  if (manager === "pnpm") {
    return "pnpm install";
  }
  if (manager === "yarn") {
    return "yarn install";
  }
  if (manager === "bun") {
    return "bun install";
  }
  return "npm install";
}

function runScriptCommand(manager: string, script: string): string {
  if (manager === "pnpm") {
    return `pnpm ${script}`;
  }
  if (manager === "yarn") {
    return `yarn ${script}`;
  }
  if (manager === "bun") {
    return `bun run ${script}`;
  }
  if (script === "test" || script === "start") {
    return `npm ${script}`;
  }
  return `npm run ${script}`;
}

function pythonInstallPrefix(manager: string | undefined): string {
  if (manager === "uv") {
    return "uv pip install";
  }
  return "python -m pip install";
}

function pythonProjectInstallCommand(manager: string | undefined): string {
  if (manager === "uv") {
    return "uv pip install -e .";
  }
  if (manager === "poetry") {
    return "poetry install";
  }
  if (manager === "pdm") {
    return "pdm install";
  }
  return "python -m pip install -e .";
}

function dedupeCommands(rows: CommandRow[]): CommandRow[] {
  const seen = new Set<string>();
  const deduped: CommandRow[] = [];
  for (const row of rows) {
    const key = `${row.purpose}\0${row.command}`;
    if (!seen.has(key)) {
      seen.add(key);
      deduped.push(row);
    }
  }
  return deduped;
}

function formatList(values: readonly string[] | undefined): string {
  if (!values || values.length === 0) {
    return "none detected";
  }
  return values.map((value) => `\`${value}\``).join(", ");
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function escapeBackticks(value: string): string {
  return value.replace(/`/g, "\\`");
}

function joinLines(lines: string[]): string {
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`;
}
