export const GENERATED_MARKER =
  "<!-- Generated by repo-to-agents. Edit source repository patterns, then rerun. -->";

export const SUPPORTED_TARGETS = ["agents", "copilot", "cursor", "claude"] as const;

export type Target = (typeof SUPPORTED_TARGETS)[number];

export interface PackageManagerFacts {
  name: "npm" | "pnpm" | "yarn" | "bun";
  version?: string;
  source: string;
}

export interface PackageJsonFacts {
  name?: string;
  packageManager?: PackageManagerFacts;
  scripts: Record<string, string>;
  dependencies: string[];
}

export interface PythonFacts {
  projectName?: string;
  manager?: "uv" | "poetry" | "pdm" | "pip";
  pyproject: boolean;
  requirementsFiles: string[];
  tools: string[];
}

export interface GoFacts {
  modulePath?: string;
}

export interface RustFacts {
  packageName?: string;
}

export interface MakeFacts {
  targets: string[];
}

export interface DockerFacts {
  dockerfiles: string[];
  composeFiles: string[];
}

export interface ReadmeFacts {
  path: string;
  title?: string;
  description?: string;
}

export interface DirectoryFacts {
  path: string;
  purpose: string;
}

export interface RepoFacts {
  root: string;
  name: string;
  readme?: ReadmeFacts;
  packageJson?: PackageJsonFacts;
  python?: PythonFacts;
  go?: GoFacts;
  rust?: RustFacts;
  make?: MakeFacts;
  docker?: DockerFacts;
  tsconfig?: string;
  testConfigs: string[];
  githubActions: string[];
  directories: DirectoryFacts[];
  languages: string[];
  frameworks: string[];
  configFiles: string[];
  files: string[];
}

export interface GeneratedOutput {
  target: Target;
  path: string;
  content: string;
}

export interface FileStatus {
  path: string;
}

export interface WriteReport {
  written: FileStatus[];
  unchanged: FileStatus[];
  protected: FileStatus[];
}

export interface CheckReport {
  missing: FileStatus[];
  stale: FileStatus[];
  unchanged: FileStatus[];
}
